version: '3.4'

services:
  redis:
    image: redis:alpine

  mongodb:
    image: mongo

  wasteman:
    image: wasteman:latest
    build:
      context: .
      dockerfile: ./src/WasteMan.Web.Api/Dockerfile
    depends_on:
      - redis
      - mongodb